server:
  port: 8081

spring:
  application:
    name: PRODUCTS
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/product_ms
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4646/eureka/

