eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4646/eureka


server:
  port: 8084

spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/auth_ms
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
