server:
  port: 8080

spring:
  application:
    name: api-gateway

  session:
    store-type: redis
  redis:
    host: localhost
    port: 9123

  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: product-service
            uri: lb://PRODUCTS
            predicates:
              - Path=/api/v1/product/**

          - id: order-services
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/api/v1/order/**

          - id: user-service
            uri: lb://USER
            predicates:
              - Path=/api/v1/user/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4646/eureka/