server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: product-service
            uri: lb://PRODUCTS
            predicates:
              - Path=/api/v1/product/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4646/eureka/