spring:
  application:
    name: Products
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/product_ms
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka # Replace with your Eureka server URL
server:
  port: 8081
