spring:
  application:
    name: Eureka Server

server:
  port: 4646


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:4646/eureka/